<? 
	include("includes/configuration.php");
	include(DIR_INCLUDES.'functions/orders.php');
	
	include (DIR_INCLUDES.'header.php'); 

?>
<!--header ends-->
<!--content starts-->
<link href="styles/style.css" rel="stylesheet" type="text/css" />
<table cellpadding="0" cellspacing="0">
  <tr>
    <td width="70%"><table cellpadding="0" cellspacing="0" width="724" align="center">
        <tr>
          <td height="12" valign="bottom" align="left"><img src="images/top_left_curve.png" /></td>
          <td style="background:url(images/shadow_top.png) repeat-x bottom; font-size:2px;">&nbsp;</td>
          <td><img src="images/top_right_curve.png" /></td>
        </tr>
        <tr>
          <td width="17" style="background:url(images/left_shadow.png) repeat-y right;width:17px;"><img src="images/blank.png" /></td>
          <td><form method="post" action="<?=$_SERVER['PHP_SELF']?>" >
              <div style="width:800px; margin:auto;background:#FFFFFF;">
                <div style="height:10px;"></div>
                <div style="background-color:#ff6e01;color:#FFFFFF;font-size:25px;font-family:Arial, Helvetica, sans-serif; padding-left:20px;"><b>Terms And Conditions</b></div>
                <div style="height:10px;"></div>
                <div style="margin-left:20px;margin-right:30px;border:solid 1px #cecece;">
                  <div style="margin-left:20px;margin-top:20px;margin-right:30px;" class="text_blue">
				    <p><strong>BY CLICKING &quot;PLACE ORDER&quot; YOU                    AGREE TO ALL THE &quot;TERMS OF SERVICE&quot; LISTED BELOW</strong><br />
                      <br />
                      <strong>100% MONEY BACK GUARANTEE IS FOR CARICATURE TOONS                    ONLY.</strong><br />
If your not 100% happy with the final result, based on                  your original instructions and photo's supplied and                  after giving the Artist the ample opportunity to make                  the necessary changes, we refund your money. No                  questions asked. The 100% Money back guarantee does not                  apply if you decided to change Artists after you have                  placed your initial order. Each Artist is freelance and                  independent of each other and you are committed to their                  style to completion. Once you have approved the final                  image, which is defined by you downloading the                  Caricature Toon and the proof watermark being removed,                  you are no longer eligible for a refund. Once the final                  Character Toon has been downloaded you cannot requests                  changes or revisions without paying an additional cost.<br />
<br />
<strong>100%SATISFACTION GUARANTEE FOR PRODUCTS AND                    MERCHANDISE</strong><br />
If products or merchandise are lost or damaged in                  shipping, or arrives with any workmanship defects, we                  will replace it. All we ask is that you report any                  problems to us within 48 hours of accepting shipment.                  After an order has been placed we do not allow order                  cancellation or refunds.<br />
<br />
<strong>OWNERSHIP OF FINAL CARICATURE TOON</strong><br />
All Caricature Toons ordered are 100% Royalty Free to                  the customer to be used how they like. Caricature Toons                  reserves the right to use any Caricature Toon and                  original Images supplied in their marketing materials or                  promotional materials without formal consent of the                  customer.<br />
<br />
<strong>PRIVACY POLICY</strong><br />
We do not share or sell your personal information or                  email address with anyone. From time to time we may send                  you information or special offers, however, if you                  prefer not to receive them, you can easily unsubscribe                  at any time. We do reserve the right to use your                  Caricature Toon and original images supplied in our                  marketing or promotional materials.<br />
<br />
This Caricaturetoons Terms of Service Agreement (the                  &quot;Agreement&quot;) is an agreement between you and                  Caricaturetoons, Inc (&quot;Caricaturetoons&quot;). This                  Caricaturetoons Web site and the products and services                  offered thereby (the Service) is owned and operated by                  Caricaturetoons, Inc. The following terms and conditions                  apply to your use of our Services. Please read this                  Agreement carefully before you enter our Web site. In                  this Agreement, &quot;you&quot; or &quot;your&quot; means any person or                  entity using the Service. Unless otherwise stated, &quot;we&quot;                  or &quot;our&quot; will refer collectively to Caricaturetoons,                  Inc. and its subsidiaries, affiliates, directors,                  officers, employees, agents and contractors.<br />
<br />
By clicking &quot;I Agree&quot; or &quot;Order Now&quot; you agree to the                  Agreement, the Caricaturetoons Privacy Policy, and any                  documents incorporated by reference. You further agree                  that this Agreement forms a legally binding contract                  between you and Caricaturetoons, and that this Agreement                  constitutes &quot;a writing signed by You&quot; under any                  applicable law or regulation effective as of the date                  you click &quot;I Agree or Buy Now&quot;. I also understand that                  as a result of agreeing to this statement, a digital                  confirmation of my acceptance will be marked in my                  Caricaturetoons account record as verification of my                  approval of this condition.<br />
<br />
<strong>ACCOUNTS</strong><br />
A. Eligibility To use the Service, you must open an                  account with Caricaturetoons, which means you must                  register with Caricaturetoons on the Web site and agree                  to the terms of this Agreement (Account). You must be at                  least 18 years of age to use the Service. By using our                  Service, you certify that you are at least 18 years of                  age and that you agree to be bound by these terms and                  conditions of use. If you do not agree to be bound by                  this Agreement or if you are not at least 18 years of                  age, please immediately exit the site. B. Use Your                  Caricaturetoons Account is available for your                  non-commercial, personal use. Your Account can be                  utilized to post photographs that you want to let other                  specified people view and purchase. You can also use                  your Account to view photographs in other Accounts if                  you have been authorized by that account holder. Any                  photographs in your account are password protected                  unless you allow other Caricaturetoons Account holders                  access to such photographs. Caricaturetoons reserves the                  right to cancel or discontinue Accounts which have been                  inactive for more than 60 days. We may do so at our                  discretion after sending an email warning to the address                  you used when you set up your Account. If you do not                  respond to the email within 10 days, your account may be                  removed. You may not use your Account to create an                  Internet link to eBay or any other web site without the                  express written permission of Caricaturetoons.<br />
<br />
<strong>PHOTOGRAPHS AND PRODUCTS</strong><br />
A. You can purchase the photographs featured on our Web                  site Caricaturetoons in the form of photographic prints,                  or other photographic products such as picture frames or                  photo-albums (collectively, the &quot;Products&quot;). You                  acknowledge that all Products are custom made to your                  order and have no market beyond your purchase thereof.                  As such, all Products are non-returnable and payment for                  all Products is required to be made in full in advance.                  All items purchased through Caricaturetoons and shipped                  to you are subject to a shipment contract under which                  the risk of loss and title for such items pass to you                  upon our delivery to our shipping carrier. B. You may                  not reproduce, display, transmit, distribute or                  otherwise exploit the Products, or any portion thereof,                  in any manner, including, without limitation, print or                  electronic reproduction, publication or any display of                  photographs, without the prior written consent of                  Caricaturetoons. While you can add captions and                  descriptions to the photographs in your account in                  accordance with the terms hereof, you agree not to                  otherwise modify, alter or otherwise manipulate any                  Product, including without limitation, adding other                  material to a Product, without Caricaturetoons's prior                  written consent. C. While Caricaturetoons uses                  reasonable efforts to ensure compliance with applicable                  laws relating to rights of privacy or publicity,                  including the use of subject releases when necessary and                  requiring the photographers to screen the photographs                  posted on the Web site, it makes no representations or                  warranties as to the accuracy, correctness or                  reliability of the photographs, nor can Caricaturetoons                  ensure that all persons depicted in the photographs have                  consented to the display of their image on this Web                  site. If your photograph appears on this Web site and                  you wish to have it removed, please copy the thumbnail                  image and e- mail it to <a moz-do-not-send="true" href="mailto:helper@caricaturetoons.com">helper@caricaturetoons.com</a> with                  a description of why you would like it removed.<br />
<br />
<strong>YOUR COPYRIGHTS</strong><br />
Caricaturetoons respects the copyrights, real and                  implied, of photographers, Artists and/or other                  copyright holders. Caricaturetoons will not knowingly                  print and/or distribute images without the consent of                  the creator or owner of the copyrights. The copyrights                  in the photographs are owned by the photographers                  thereof who have licensed to Caricaturetoons the right                  to post them on the Web site and provide the Services                  offered. Caricaturetoons makes no claim of ownership to                  any images uploaded to our servers by our customers.                  Since we cannot research every image transmitted to us                  or printed by us, it is your sole responsibility to                  ensure that you have the necessary authorizations and/or                  permissions to use the images. If you believe your                  copyright in a work has been violated through this                  service, please contact Caricaturetoons for notice of                  claims of copyright infringement at <a moz-do-not-send="true" href="mailto:toonhelper@caricaturetoons.com">toonhelper@caricaturetoons.com</a> Caricaturetoons, Inc., 1890 Beaver Ridge Circle, Suite                  A, Norcross Georgia, 30071, 415.935.6285<br />
<br />
<strong>CONTENT</strong><br />
A. Limits You may NOT post or obtain any content using                  the Web site which: Is threatening, obscene,                  pornographic or profane material or any other material                  that could give rise to any civil or criminal liability                  under applicable law. Caricaturetoons recommends you                  use, an &quot;adult-content&quot; warning label when pictures are                  being shared that include legal adult content; Infringes                  rights of privacy, publicity or copyrights or otherwise                  uses content without the permission of the owner of                  these rights and the persons (or their parents or legal                  guardians, where applicable) who are shown in the                  material. B. Content Monitoring While Caricaturetoons                  does not and cannot review all content provided to it,                  and is not responsible for such content, Caricaturetoons                  reserves the right to delete, edit or rearrange content                  that it, in its sole discretion, deems abusive,                  defamatory, obscene or in violation of copyright or                  trademark laws or otherwise unacceptable. You                  acknowledge that any content may be removed, published,                  copied, modified, transmitted and displayed by                  Caricaturetoons for the purposes of delivering the                  offered services. All content provided by a user of this                  service is the sole responsibility of that user, not                  Caricaturetoons. C. Unauthorized Content If you send any                  image to the Web site which violates any term of this                  Agreement or any applicable law or regualtion, for                  example copyrighted or pornographic material,                  Caricaturetoons reserves the right to retain the image                  and charge your Account the full amount for the Service                  that you requested.<br />
<br />
<strong>DISCLAIMERS</strong><br />
THIS WEB SITE AND ITS CONTENT (INCLUDING WITHOUT                  LIMITATION THE PHOTOGRAPHS) ARE PROVIDED &quot;AS IS&quot; AND                  CARICATURE TOONS MAKES NO REPRESENTATIONS OR WARRANTIES                  OF ANY KIND, EITHER EXPRESS OR IMPLIED, ABOUT THE IMAGES                  OR WEB SITE INCLUDING, WITHOUT LIMITATION, WARRANTIES OF                  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR                  NON-INFRINGEMENT, TO THE FULLEST EXTENT PERMISSIBLE                  UNDER APPLICABLE LAW. CARICATURE TOONS DOES NOT WARRANT                  THAT ACCESS TO THE WEB SITE OR ITS CONTENTS WILL BE                  UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE                  CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT                  AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL                  COMPONENTS. CARICATURE TOONS DOES NOT WARRANT OR MAKE                  ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF                  THE USE OF ANY CONTENT ON THIS SITE IN TERMS OF ITS                  CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.                  ACCORDINGLY, YOU ACKNOWLEDGE THAT YOUR USE OF THIS WEB                  SITE IS AT YOUR OWN RISK. YOU (AND NOT CARICATURE TOONS)                  ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING,                  REPAIR, OR CORRECTION RESULTING FROM COMPUTER                  MALFUNCTION, VIRUSES OR THE LIKE. APPLICABLE LAW MAY NOT                  ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE                  EXCLUSION MAY NOT APPLY TO YOU.<br />
<br />
<strong>LIMITATION OF LIABILITY</strong><br />
Neither Caricaturetoons, nor its licensors or                  representatives, shall be responsible or liable for any                  damages of any kind including, without limitation, lost                  business or profits, direct, indirect, incidental,                  consequential, compensatory, exemplary, special or                  punitive damages that may result from your access to or                  use of either this Web site or the photographs or                  Products. You acknowledge that the photographers are                  independent contractors of Caricaturetoons and if you                  are not satisfied with the photographs or Products in                  any way, you shall look solely to such photographer(s),                  and not to Caricaturetoons, for any damages and/or                  claims whatsoever relating to the photographs or                  Products.<br />
<br />
<strong>INDEMNIFICATION</strong><br />
In the event that you reproduce, display, transmit,                  distribute or otherwise exploit the photographs or                  Products, or any portion thereof, in any manner not                  authorized by Caricaturetoons, or if you otherwise                  infringe any intellectual property rights or any other                  rights relating to the photographers, photographs,                  Products or this Web site, you agree to indemnify and                  hold Caricaturetoons, its subsidiaries, affiliates,                  licensors and representatives, harmless against any                  losses, expenses, costs or damages, including reasonable                  attorneys' fees, incurred by them as a result of                  unauthorized use of the photographs or Products and/or                  your breach or alleged breach of these terms of this                  Agreement.<br />
<br />
<strong>OWNERSHIP OF OUR WEB SITE</strong><br />
All of the content (other than the photographs) on our                  Web site, including without limitation, the graphics,                  design, and look and feel are owned by Caricaturetoons                  and are protected by United States and international                  copyright, trademark, patent, trade secrets and other                  intellectual property rights protection. The                  Caricaturetoons logos are trademarks owned by                  Caricaturetoons and may not be used or reproduced                  without our written permission. In addition, you may not                  reverse engineer, de-compile, or otherwise disassemble                  software included on this Web site.<br />
<br />
<strong>THIRD-PARTY SOFTWARE</strong><br />
Caricaturetoons may make software from third-party                  companies available to you. To download such software,                  you may be required to agree to the respective software                  licenses and/or warranties of such third-party software.                  Each software product is subject to the individual                  company's terms and conditions, and the agreement will                  be between you and the respective company. This means                  that Caricaturetoons does not guarantee that any                  software you download will be free of any contaminating                  or destructive code, such as viruses, worms or Trojan                  horses. Caricaturetoons does not offer any warranty on                  any third-party software you download using the Web                  site.<br />
<br />
<strong>LINKED INTERNET SITES</strong><br />
Caricaturetoons may make software from third-party                  companies available to you. To download such software,                  you may be required to agree to the respective software                  licenses and/or warranties of such third-party software.                  Each software product is subject to the individual                  company's terms and conditions, and the agreement will                  be between you and the respective company. This means                  that Caricaturetoons does not guarantee that any                  software you download will be free of any contaminating                  or destructive code, such as viruses, worms or Trojan                  horses. Caricaturetoons does not offer any warranty on                  any third-party software you download using the Web                  site.<br />
<br />
A. Third Party Links<br />
Our Web site may provide a link to other sites by                  allowing the user to leave this Site to access                  third-party material or by bringing the third-party                  material into this Web site via hyperlinks and framing                  technology (a &quot;Linked Site&quot;). Caricaturetoons has no                  discretion to alter, update, or control the content on a                  Linked Site. The fact that Caricaturetoons has provided                  a link to a site is not an endorsement, authorization,                  sponsorship, or affiliation with respect to such site,                  its owners, or its providers. There are inherent risks                  in relying upon using, or retrieving any information                  found on the internet, and Caricaturetoons, urges you to                  make sure you understand these risks before relying                  upon, or retrieving any such information on a Linked                  Site. It is your responsibility to become familiar with                  each site's privacy and other policies and terms of                  service, and to contact that site's webmaster or site                  administrator with any concerns. B. You May Not Create a                  Link to Our Web site Caricaturetoons prohibits caching,                  unauthorized hypertext links to the Web site and the                  framing of any content available through the Web site.                  Caricaturetoons reserves the right to disable any                  unauthorized links or frames and specifically disclaims                  any responsibility for the content available on any                  other Internet sites linked to the Web site. You may not                  create a link to our Website without the express written                  permission of Caricaturetoons.<br />
<br />
<strong>INTERNATIONAL USE</strong><br />
Caricaturetoons makes no representation that materials                  on this site are appropriate or available for use in                  locations outside of North America, and accessing them                  from territories where their contents are illegal is                  prohibited. Those who choose to access this site from                  other locations do so on their own initiative and are                  responsible for compliance with local laws.<br />
<br />
<strong>OTHER TERMS</strong><br />
These terms shall be governed by and construed in                  accordance with the laws of the Province of Ontario,                  without giving effect to any principles of conflicts of                  law. You agree that any action at law or in equity                  arising out of or relating to these terms shall be filed                  only in the state or federal courts located in Toronto,                  Ontario and you hereby consent and submit to the                  personal jurisdiction of such courts for the purposes of                  litigating any such action. If any provision of these                  terms shall be unlawful, void, or for any reason                  unenforceable, then that provision shall be deemed                  severable from these terms and shall not affect the                  validity and enforceability of any remaining provisions.                  You acknowledge and agree that except as specified                  herein, no representations, warranties or promises of                  any kind have been made to you by Caricaturetoons                  regarding the use of the Web site or the use or purchase                  of the photographs or the Products.		            </p>
</div>
                  <div style="height:20px;"></div>
                  <div style="height:25px;"></div>
                </div>
                <div class="height20"></div>
              </div>
            </form></td>
          <td style="background:url(images/right_shadow.png) repeat-y left"><img src="images/blank.png" /></td>
        </tr>
        <tr>
          <td><img src="images/btm_left_curve.png" /></td>
          <td style="background:url(images/shadow_btm.png) repeat-x top;"><img src="images/blank.png" /></td>
          <td><img src="images/btm_right_curve.png" /></td>
        </tr>
      </table></td>
  </tr>
</table>
<!--content ends-->
<!--footer-->
<? include (DIR_INCLUDES.'footer.php') ?>
